### ISSUE TITLE
grunt build failed 

### ISSUE THREAD

**Issue by turgayh** [smddzcy/cv#12]
Hi Samed
when I run 'grunt build' or ' grunt' command  I have a problem like that:
`╰─$ yarn grunt build
yarn run v1.17.3
$ /Users/hakan/Desktop/cv/node_modules/.bin/grunt build
Running "setDev:false" (setDev) task

Running "clean:prebuild" (clean) task
>> 4 paths cleaned.

Running "less:dist" (less) task
>> 2 stylesheets created.

Running "autoprefixer:dist" (autoprefixer) task
>> 2 autoprefixed stylesheets created.

Running "copy:all" (copy) task
Created 2 directories, copied 9 files

Running "cssmin:dist" (cssmin) task
>> 2 files created. 129.69 kB → 121.34 kB

Running "bake:dist" (bake) task
Warning: str.trim is not a function Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
Warning: str.trim is not a function Use --force to continue.
how can I  fix that ?

**Comment by smddzcy** [comment]
It might be a bug with the code - maybe I'm forcing you to enter some info that was supposed be an _optional_ field - it might be just that you're missing a required field in one of the json files.

It looks like you solved the issue but if it's a bug in the code, please open a PR with the fix 👌
