### ISSUE TITLE
Optional font size

### ISSUE THREAD

**Issue by smddzcy** [smddzcy/cv#2]
# About

Font-size should be configurable and one should be able to change it easily without changing tens of lines of CSS code.

**Note:** Relative sizes of the fonts must stay the same.

**Comment by abettermap** [comment]
I'll take this one too. I'll use the same strategy as I do for the colors.

**Comment by smddzcy** [comment]
Alright, just make sure to replace pixels with `rem`s (preferably, easy to write) or `em`s.

**Comment by smddzcy** [comment]
https://github.com/smddzcy/cv/commit/f3e25edfdaada452212a5ff39f78cb76a5c84db6 closed it.
